.PHONY: 1,2,3,4
1:
	g++ cryp.cpp -o cryp.exe
	./cryp.exe
	rm cryp.exe
2:
	g++ anticryp.cpp -o anticryp.exe
	./anticryp.exe
	rm anticryp.exe
3:
	g++ map.cpp -o map.exe
	./map.exe
	rm map.exe
4:
	g++ stat.cpp -o stat.exe
	./stat.exe
	rm stat.exe