.PHONY: 0,1,2,3,4,5
0:
	rm *.exe
1:
	g++ 1-cryp.cpp -o cryp.exe
	./cryp.exe
	rm cryp.exe
2:
	g++ 2-anticryp.cpp -o anticryp.exe
	./anticryp.exe
	rm anticryp.exe
3:
	g++ 3-map.cpp -o map.exe
	./map.exe
	rm map.exe
4:
	g++ 4-stat.cpp -o stat.exe
	./stat.exe
	rm stat.exe
5:
	g++ 5-test.cpp -o test.exe
	./test.exe
	rm test.exe